api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "hsdelivery"
type = "function"
uid = "52e74fbb-d0d3-3f2a-7d80-0ec1e18c8f840b18c413"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
